name: Compile & Release

on:
    push:
        paths:
            - '**.gradle'
            - '**.properties'
            - '**/src/**'
        branches:
            - v4
            - v5

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                  java-version: 11
            - name: Upload to Maven
              run: ./gradlew publish curseforgePublish --stacktrace
              if: |
                  !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.pull_request.title, '[ci skip]')
              env:
                  MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
                  curse_api_key: ${{ secrets.CF_API_KEY }}
